users:
  - name: devops
    groups: ["developers"]
    shell: /bin/bash
    state: absent
    sudo: true
    ssh_key: devops.pub

  - name: admin
    groups: ["admins"]
    shell: /bin/bash
    state: present
    sudo: true
    ssh_key: admin.pub

  - name: testuser
    groups: ["test"]
    shell: /bin/bash
    state: absent
    sudo: false
