groups_to_create:
  - name: dbadmins # Database administration group
    state: present

  - name: dbbackup # Database backup group
    state: present

users_to_create:
  - name: arjun # DB admin user
    group: dbadmins
    state: present

  - name: amit # DB backup user
    group: dbbackup
    state: present
    
apps_to_install:
  - postgresql
  - python3-psycopg2
