groups_to_create:
  - name: webadmins # Web administration group
    state: present

  - name: developers # Development group
    state: present

users_to_create:
  - name: moiz # Web admin user
    group: webadmins
    state: present

  - name: rahul # Developer user
    group: developers
    state: present

apps_to_install:
  - nginx
  - git
